# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab" do
  name "bab"
  desc "Bab CLI - A simple task runner"
  homepage "https://github.com/bab-sh/bab"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "c0b921eb6923dadde3c4e8d8998846195979fdb368b84e1ccb04b5d5c71c4a98"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "50e37bf8f96ff3bf1b7864f208b4fbb6eb9b96c22cf0c072116b6d3873f8da68"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "86fa812ea08537ce441c4413d00f680bdfd3b88c6a0e65780a24b9bc58f665a7"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "090fa7d3fa627f7623c38156a406082162565286d030d8d0e93e4ba9d68bb3eb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
