# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab" do
  name "bab"
  desc "Bab CLI - A simple task runner"
  homepage "https://github.com/bab-sh/bab"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_Darwin_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "cba8ef58405c4d80521ec6508a6ee7936c4b73ebb4c93ad91eee3da2ed2de6ff"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_Darwin_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "c5d372726657baccc10c76b53e57fbc4c13f132e147d9b7be5f3476cedcbb70f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "ae49f45681d62a3716f31c0af796f62baf1959b1a6148238708e083a6c2a4a24"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "6abd7f2b8520a645d992f76a4daf42a7c1cbfd93f0f714ed1bb39b1ea8f5d63c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
