# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab" do
  name "bab"
  desc "Task runner for defining project commands in YAML"
  homepage "https://github.com/bab-sh/bab"
  version "0.7.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "fd0d7b4f84386f4b8ef623197ec687350e8b2bcf4565f61f5a2621115172e5fb"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "2a3e915d897157357b0b86eb0041d71dc22c2f1b23e302510d81b2e5e847583a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "35419f76b10b607a7bbc746968be1a7fbfa45040dd7b85a930e350f4655b302c"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "160b9ec3beff3b2074a4144f56e8ba125188dcd1e77cc1b18ba8020a7e46d5bf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
