# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.5" do
  name "bab@0.5"
  desc "Task runner for defining project commands in YAML (v0.5.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.5.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "42a734474f02cac512756cf1d5fbc618b246f337e1a22474a1749581e9fa4dfe"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "955f2088f6d8328081761f7a32ccf27165d61b6e13ded038f233898ce1368756"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "569b2c9ce340f9a54257e45c96ee578f63c436b09a4739ddfe32172f0674b0c8"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "3f47a68828d7bd765a25abd1f9a50163c47cc606380dd1d78ddfe3c76adffadb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
