# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.2" do
  name "bab@0.2"
  desc "Custom commands for every project (version 0.2.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.2.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "62861d33ed8a88bafc7985a2b885ef8c48a1e382c04c502c78d9a919edf8b617"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "9a936680e5ad6167002215c73a666bd76f87d3f0a97fc6422231eee32259b7cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "5e2a30bbce1d07f7ac74468b0b087ea125fa7eecd930dbac0effe1fc57e8c01c"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "c8d4df54fcd36e51aa74f26b7f4a524fd6a3e670f0e6d317f0435e68b10ef0cd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
