# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.2" do
  name "bab@0.2"
  desc "Custom commands for every project (version 0.2.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "b75a398c0870887cd909c3e3d9d3e735aec7270173055ac86ecfdb691f16f994"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "bfc5513645f508da1d1876a952a22a65b28d7008467bf494766c55b53e47f2d8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "9c2bba008f3cd42f8d6c1808655d3a97c8cd18be7d25273cb13b023b4ecb51dd"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "f0c86ca7c72f2d307c11eaa1b75465cf7a9d025cdf62b94e5d00769c5fa1cc51"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
