# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.4" do
  name "bab@0.4"
  desc "Custom commands for every project (version 0.4.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "f589178ee937ecec203aa5188f4787194cbdc685fe761de9ff97f0259a4a22c5"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "1a7c5755bd17b6552e5952e30dd3956ade849d90c68ca52d8ea44990032c90da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "0daf414c6f8fdfb9686870124863a2a92edc67232047ca09a6f651b8e00f9dbe"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "6b9aaa383c893a3cca0de75633b904df89a96a988ac3ec063859e0a4be9c02c8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
