# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.5" do
  name "bab@0.5"
  desc "Custom commands for every project (version 0.5.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "5ee925676e45d8a3c81e3525ff8e724eb83bf448d2496e80034f052671628bd5"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "c8224373eee8047d7f08c76f7021b75fa8795d55eca902101770797e420aff67"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "04a9ea39ab29af384ebdec8d47468b071fb859503d3560b2b07e7d2465884a95"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "bad937d088f4cba0284ee2ea713cc59ee26a15ea889696767965edb415d8f5bf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
