# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.7" do
  name "bab@0.7"
  desc "Task runner for defining project commands in YAML (v0.7.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "5032a61a290343b3cb18cd42f4fdfb4ea41b0d8abfa1b0f2807a0a74d4d6ac3c"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "da3c29f56b991dd57f542c7245ea707efea79dd440d873cf20595418e42274dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "c63c7e14411ca6af9a83b22a56724083a004e80efe53b2aec184c779018f1589"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "24726bc7850780341afd1628453edff9fa0e2cf8e4cba4bdad2376ae89bb3ed9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
