# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.3" do
  name "bab@0.3"
  desc "Bab CLI - A simple task runner (version 0.3.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "7d834c4249930f699b4baea53b6550548f5c108b1d2bf137bb398f2ca10970d7"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "9fd11fd844addc42ab701668259118e5e40874d3380e2de86d447b6b0f2c7b56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "1990d2d0c61cbba1feded616afc725f8816d232a05c2259240aabe4c6d3be320"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "0d7a84573108f3b455d9691cd08c4609bb5816f6982d3157e211efbb990c4d0b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
