# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.6" do
  name "bab@0.6"
  desc "Task runner for defining project commands in YAML (v0.6.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.6.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "3b4b57cb73ed4009e6bbbe767fcf8cac6cc150b0a2d1e9578a79a75601929a31"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "2a35fe9c72b8056b9112cc05e0cdba094f527e9d506b75bfef32dadc71413550"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "7f510a6cd3736bdd64c2dd880ce55fb73329a324f251d75a7601347ae7b98403"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "023f706fea061d902ccb3d4983c9eb395737b2c472dc6e79ae3ec25722eb71d9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
