# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.6" do
  name "bab@0.6"
  desc "Task runner for defining project commands in YAML (v0.6.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.6.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "745c2faa728981b0b82bba0f4c20d8c0178c919d4779ced71a16388b1929b6f2"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "5521df67344cc5ce813ee70597ddc9acbb2b4316e1b6b5e207ed83c562ceba64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "f3e250312b2c8637c7be01c877066bae2a4a57f1f87ee7d5742f80a72723d5c6"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "65685e0bcf00fc37e14a3f4956dbcc3b962328e6bff46702b09be7b3049524fe"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
