# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.1" do
  name "bab@0.1"
  desc "Bab CLI - A simple task runner (version 0.1.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab@0.1"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "5c646e87ace244d09638025610ff73343083db518bc77659bc82bc311723fa2c"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "24d6ad4391374739d8e8599039add252a01dcdf9338b5308fa03b1345ec08bfc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "1988d2a8128905bc51e27ba7b72b0f0cc74365167e355da3da47f33ae3c81998"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "12441c796155d8bb8dee64a7bb56194201a03ebccf0d97de7dc6f2a965286826"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
