# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.6" do
  name "bab@0.6"
  desc "Task runner for defining project commands in YAML (v0.6.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "525842e8907668ea6141271495a1ffb00cbe9dfe2b31d3ba1faf8b5625e9948e"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "bcee5d4a03d8f5e8e255173aa729b135e9ef4348b2710062163ade05fde1f678"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "6c24661fc806286c1c4ebcacaf82fa2beb28368b4baacee7e93a3ca7e9cbbd85"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "b2c2d8a579e63cb13688f2b98c009c7e4cc789968c99168553eef08979278b03"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
