# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.7" do
  name "bab@0.7"
  desc "Task runner for defining project commands in YAML (v0.7.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.7.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "454dc42c351fc7a1b80bd0484cced97a1e40479e9a76f3ada0b9bc0c6fb99177"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "9477989dbbd97a75db76ba65a278f7bc8dd07bd9160f75ce299b0c3e6e414ec2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "7f34800a3679fa942442facb9b0b14dd5ae4061bc59df1e16047d054cef972da"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "064c5d0ce75185c0c4e08520a1fb430da369b840b32e4509f3d989c8f1ad520b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
