# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.0" do
  name "bab@0.0"
  desc "Bab CLI - A simple task runner (version 0.0.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_Darwin_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "2a2358e083148d2b518bd2b28d73f5914c166edc010f73251c0ac9601a90d624"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_Darwin_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "ca3cc12596c1d76f94d75f25b8d617c9759ae229697d27a7b5016f1ef806e7f4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "c07405b528f2b6601f4c3903c8e669b2d1dbe1d199bfefa43a060085973b9ded"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "7f8cf251faf70714153ae28f18fca3d2a317d2d61741fa59709d79e861f7acb7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
