# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.3" do
  name "bab@0.3"
  desc "Custom commands for every project (version 0.3.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.3.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "d8558036d4209a6491c14c4774c6d64a02ddc8060e75c51203a5ae1f2959869e"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "27f68325d922b92c99f3120dd25237375d398cbff25d736e85d03b914596f651"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "70f8c5cfe32a3adf497421acc5fc79d07ef8589426c9474a9739ae6856496697"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "52a4e45b4d57fdf0d99ea32d5c04d882d82111b3ef26c93c5d54c5bde03a46ea"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
