# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.0" do
  name "bab@0.0"
  desc "Bab CLI - A simple task runner (version 0.0.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "39630f8c058e43e654435bae9922b695531db07690690cb099418cf771bde161"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "28e1c7f74efa4c2eb09fa34681c7d68209d8204da1e0404ad2c4ab6cecea341e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "d5e6f02a0ce9b835472aa28f217f81b10d664a6cedf607cfb9439bdca9e3443c"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "b76cd322aec1a2208ab278c16c9660831bc750d92c604daa08753bffa1d8d5c0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
