# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.0" do
  name "bab@0.0"
  desc "A Simple Task Runner (version 0.0.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "f74932cd2f5cc0f083e99bb03c4003da3b86a35c342b46698fe1eeae364d924c"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "76e484dc48ec064be7c601377219c79cbcad01e155cfb28d0e7e79123c343bea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "dbf0eb0c9bce6e5d431c82efa12ef4872ae06d4c9f0e27ff9fb94d1503c31118"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "05b89c161520a91aa35b8ec8d239564063ad7983e1b0c743316f742acf6e4c3f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
