# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.1" do
  name "bab@0.1"
  desc "Bab CLI - A simple task runner (version 0.1.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab@0.1"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "8b0af3a985bcf372f0de1e4641c1f24a23bb4b27038f23da5bd11c5eb2f3bcb3"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Darwin_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "cc9220f5c1b3344410fa261607d42f0b6449b8b252b2c3e598771415e54d4e56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "fee7199ffe6113707ec783dfc2d16ae2c32f132242517c7e77b3538de2754088"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/#{version}/bab_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "2147b710ede43c55735b7a20431a4d390a97351423313c5f7bc717e049867aaf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
