# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.2" do
  name "bab@0.2"
  desc "Custom commands for every project (version 0.2.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.2.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "6a72331c7391b358e5c3430d1ffb3230f64b41ac8354a6b9fe51b91646ac67c8"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "16f0251c8fd7df9fa6ae71d2f929a5e6e2a363ee737c87b1ef0a8e978ed26c66"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "fdee9d1bc39cef7d11b1ad015ed9dbb31066f53e7e80b1af069050c51c365c29"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "727fac33397c235914b23bedb0ca783d8f468862b1df4a3b92e6650ef8f541c7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
