# This file was generated by GoReleaser. DO NOT EDIT.
cask "bab@0.4" do
  name "bab@0.4"
  desc "Custom commands for every project (version 0.4.x)"
  homepage "https://github.com/bab-sh/bab"
  version "0.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bab"
  bash_completion "completions/bab.bash"
  zsh_completion "completions/bab.zsh"
  fish_completion "completions/bab.fish"

  on_macos do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "ad117bb26fbbfef5eea3c454b63c4a66635de2dbe4831990d27001cc15dc09bd"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "3428458871efe295662c769ad34927d31e8d0e05c38ead20be92afb67b45d828"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "3b3c0ab92c11581cfb5e3eda2ae20cb00030305e1a442ea1dcd78718ee5e3776"
    end
    on_arm do
      url "https://github.com/bab-sh/bab/releases/download/v#{version}/bab_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/bab-sh/bab"
      sha256 "db5241b92d5ac5f1596f345dd18804b65636e7d8135a8434b98488a7a1e1bf04"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
    end
  end

  # No zap stanza required
end
