# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bab < Formula
  desc "Task runner for defining project commands in YAML"
  homepage "https://github.com/bab-sh/bab"
  version "0.7.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bab-sh/bab/releases/download/v0.7.13/bab_0.7.13_macOS_x86_64.tar.gz"
      sha256 "454dc42c351fc7a1b80bd0484cced97a1e40479e9a76f3ada0b9bc0c6fb99177"

      define_method(:install) do
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bab-sh/bab/releases/download/v0.7.13/bab_0.7.13_macOS_arm64.tar.gz"
      sha256 "9477989dbbd97a75db76ba65a278f7bc8dd07bd9160f75ce299b0c3e6e414ec2"

      define_method(:install) do
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bab-sh/bab/releases/download/v0.7.13/bab_0.7.13_Linux_x86_64.tar.gz"
      sha256 "7f34800a3679fa942442facb9b0b14dd5ae4061bc59df1e16047d054cef972da"
      define_method(:install) do
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bab-sh/bab/releases/download/v0.7.13/bab_0.7.13_Linux_arm64.tar.gz"
      sha256 "064c5d0ce75185c0c4e08520a1fb430da369b840b32e4509f3d989c8f1ad520b"
      define_method(:install) do
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
  end

  test do
    system "#{bin}/bab", "--version"
  end
end
