# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bab < Formula
  desc "Task runner for defining project commands in YAML"
  homepage "https://github.com/bab-sh/bab"
  version "0.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bab-sh/bab/releases/download/v0.7.3/bab_0.7.3_macOS_x86_64.tar.gz"
      sha256 "82556caaf817fe541154c2fb8cd6b65619740f51cb06bac2c6d54512a683a2c6"

      define_method(:install) do
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bab-sh/bab/releases/download/v0.7.3/bab_0.7.3_macOS_arm64.tar.gz"
      sha256 "657c91969fbf388d179e25d592d913a2a7e6483ee57cab15dfb8573d8603326d"

      define_method(:install) do
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bab-sh/bab/releases/download/v0.7.3/bab_0.7.3_Linux_x86_64.tar.gz"
      sha256 "e3fb924f55b71f0e68e0fc44c14cb3d925fcaeb873d2af21c2c2456d9b7b94f4"
      define_method(:install) do
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bab-sh/bab/releases/download/v0.7.3/bab_0.7.3_Linux_arm64.tar.gz"
      sha256 "816a49b92cfb243043ab109acc5db0d1bf9e2f7a1dcfb36918a559ab77e9a218"
      define_method(:install) do
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
  end

  test do
    system "#{bin}/bab", "--version"
  end
end
