# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bab < Formula
  desc "Task runner for defining project commands in YAML"
  homepage "https://github.com/bab-sh/bab"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bab-sh/bab/releases/download/v0.6.2/bab_0.6.2_macOS_x86_64.tar.gz"
      sha256 "745c2faa728981b0b82bba0f4c20d8c0178c919d4779ced71a16388b1929b6f2"

      def install
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bab-sh/bab/releases/download/v0.6.2/bab_0.6.2_macOS_arm64.tar.gz"
      sha256 "5521df67344cc5ce813ee70597ddc9acbb2b4316e1b6b5e207ed83c562ceba64"

      def install
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bab-sh/bab/releases/download/v0.6.2/bab_0.6.2_Linux_x86_64.tar.gz"
      sha256 "f3e250312b2c8637c7be01c877066bae2a4a57f1f87ee7d5742f80a72723d5c6"
      def install
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bab-sh/bab/releases/download/v0.6.2/bab_0.6.2_Linux_arm64.tar.gz"
      sha256 "65685e0bcf00fc37e14a3f4956dbcc3b962328e6bff46702b09be7b3049524fe"
      def install
        bin.install "bab"
        bash_completion.install "completions/bab.bash" => "bab"
        zsh_completion.install "completions/bab.zsh" => "_bab"
        fish_completion.install "completions/bab.fish"
      end
    end
  end

  test do
    system "#{bin}/bab", "--version"
  end
end
